<?php

namespace App\Controller;

use App\Model\AdModel;
use App\Model\UsersModel;


class Ad extends Table
{
    protected string $tableName = "ad";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new AdModel($config);

    }


    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Ad/show");
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData(["groupList" => $this->model->getGroupList(),
                "markaList" => $this->model->getMarka(),
                "loginList" => $this->model->getNameList()

            ])
            ->setTemplate("Ad/add_edit");
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData(["groupList" => $this->model->getGroupList(),
                "markaList" => $this->model->getMarka(),
                "loginList" => $this->model->getNameList()
                ])
            ->setTemplate("Ad/add_edit");

    }
}