<?php

namespace App\Controller;

class Guestad extends Ad
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Guest/show");

    }
}