<?php

namespace App\Controller;

use App\Model\UsersAdModel;

class Userad extends Ad
{
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new UsersAdModel($config);
        $this->model->setUserId($_SESSION['user']['id']);
//        print_r($_SESSION);
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Userad/show");
    }

    public function actionAdd(): void
    {
        $_POST["users_id"] = $_SESSION['user']['id'];
        parent::actionAdd(); // TODO: Change the autogenerated stub

    }

}